const decks = {

conditions: [

"Acute myocardial infarction",
"Aortic dissection",
"Appendicitis",
"Asthma",
"Atrial fibrillation",
"Bacterial meningitis",
"Bell palsy",
"Cirrhosis",
"Congestive heart failure",
"COPD",
"Cushing syndrome",
"Deep vein thrombosis",
"Diabetic ketoacidosis",
"Endocarditis",
"Epiglottitis",
"GERD",
"Guillain-Barré syndrome",
"Hashimoto thyroiditis",
"Hyperkalemia",
"Hypertrophic cardiomyopathy",
"Hypothyroidism",
"Inflammatory bowel disease",
"Intracranial hemorrhage",
"Lupus",
"Lyme disease",
"Malaria",
"Multiple sclerosis",
"Myasthenia gravis",
"Pancreatitis",
"Parkinson disease",
"Pericarditis",
"Pneumonia",
"Pneumothorax",
"Preeclampsia",
"Pulmonary embolism",
"Rheumatoid arthritis",
"Sepsis",
"Sickle cell disease",
"Stroke",
"Subarachnoid hemorrhage",
"Tension pneumothorax",
"Thyroid storm",
"Tuberculosis",
"Ulcerative colitis"

],

drugs: [

"Acetaminophen",
"Acyclovir",
"Albuterol",
"Amiodarone",
"Amoxicillin",
"Aspirin",
"Atorvastatin",
"Azithromycin",
"Ceftriaxone",
"Clopidogrel",
"Dexamethasone",
"Diazepam",
"Digoxin",
"Dopamine",
"Epinephrine",
"Fentanyl",
"Fluoxetine",
"Furosemide",
"Gentamicin",
"Heparin",
"Hydralazine",
"Hydrocortisone",
"Insulin",
"Ivermectin",
"Ketamine",
"Labetalol",
"Levofloxacin",
"Lisinopril",
"Lorazepam",
"Losartan",
"Metformin",
"Metoprolol",
"Midazolam",
"Morphine",
"Naloxone",
"Nitroglycerin",
"Norepinephrine",
"Omeprazole",
"Ondansetron",
"Penicillin",
"Phenylephrine",
"Prednisone",
"Propranolol",
"Rivaroxaban",
"Vancomycin",
"Warfarin"

]

};